import { useState } from "react";
import { Card, Input, Button } from "@nova/ui";
import { api } from "../lib/api";

type MfaStep = "password" | "totp_setup" | "totp" | "email_otp";

export function LoginPage({ onAuthed }: { onAuthed: (token: string) => void }): React.ReactElement {
  const [identifier, setIdentifier] = useState("admin@novaroyale.example");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  // 3FA state
  const [mfaStep, setMfaStep] = useState<MfaStep>("password");
  const [userId, setUserId] = useState<string | null>(null);
  const [totpSecret, setTotpSecret] = useState<string | null>(null);
  const [totpUri, setTotpUri] = useState<string | null>(null);
  const [totpCode, setTotpCode] = useState("");
  const [emailOtpCode, setEmailOtpCode] = useState("");
  const [devEmailOtpCode, setDevEmailOtpCode] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const submit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    setError(null); setBusy(true);
    try {
      const r = await api<
        | { accessToken: string }
        | { status: "mfa_setup"; userId: string; totpSecret: string; totpUri: string }
        | { status: "mfa_totp_required"; userId: string }
      >("/api/auth/login", { method: "POST", body: { identifier, password } });

      if ("status" in r) {
        setUserId(r.userId);
        if (r.status === "mfa_setup") {
          setTotpSecret(r.totpSecret);
          setTotpUri(r.totpUri);
          setMfaStep("totp_setup");
        } else if (r.status === "mfa_totp_required") {
          setMfaStep("totp");
        }
      } else {
        onAuthed(r.accessToken);
      }
    } catch (err) {
      setError((err as Error).message);
    } finally { setBusy(false); }
  };

  if (mfaStep === "totp_setup") {
    const handleSetup = async (e: React.FormEvent) => {
      e.preventDefault();
      setError(null); setBusy(true);
      try {
        const r = await api<{ status: string; userId: string; devEmailOtpCode?: string }>(
          "/api/auth/mfa/setup-totp",
          { method: "POST", body: { userId, token: totpCode } }
        );
        setMfaStep("email_otp");
        if (r.devEmailOtpCode) setDevEmailOtpCode(r.devEmailOtpCode);
        setTotpCode("");
      } catch (err) {
        setError((err as Error).message);
      } finally { setBusy(false); }
    };

    return (
      <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16 }}>
        <Card padded glow style={{ width: "100%", maxWidth: 420 }}>
          <h1 style={{ marginTop: 0 }}>3FA Step 2: Authenticator</h1>
          <p style={{ color: "var(--nova-text-2)" }}>Scan this key in Google Authenticator or manual enter it to set up 3FA.</p>
          <div style={{ background: "rgba(255,255,255,0.05)", border: "1px solid var(--nova-border)", padding: 16, borderRadius: 8, textAlign: "center", marginBottom: 16 }}>
            <div style={{ fontSize: 13, color: "var(--nova-text-2)", marginBottom: 4 }}>SECURITY KEY</div>
            <div style={{ fontFamily: "monospace", fontSize: 18, letterSpacing: 1, color: "var(--nova-primary)", fontWeight: "bold" }}>{totpSecret}</div>
          </div>
          <form onSubmit={handleSetup} style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <Input label="6-Digit Verification Code" value={totpCode} onChange={(e) => setTotpCode(e.target.value)} required />
            {error ? <p style={{ color: "var(--nova-danger)" }}>{error}</p> : null}
            <Button type="submit" block loading={busy}>Confirm & Continue</Button>
          </form>
        </Card>
      </div>
    );
  }

  if (mfaStep === "totp") {
    const handleVerifyTotp = async (e: React.FormEvent) => {
      e.preventDefault();
      setError(null); setBusy(true);
      try {
        const r = await api<{ status: string; userId: string; devEmailOtpCode?: string }>(
          "/api/auth/mfa/verify-totp",
          { method: "POST", body: { userId, token: totpCode } }
        );
        setMfaStep("email_otp");
        if (r.devEmailOtpCode) setDevEmailOtpCode(r.devEmailOtpCode);
        setTotpCode("");
      } catch (err) {
        setError((err as Error).message);
      } finally { setBusy(false); }
    };

    return (
      <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16 }}>
        <Card padded glow style={{ width: "100%", maxWidth: 420 }}>
          <h1 style={{ marginTop: 0 }}>3FA Step 2: Authenticator</h1>
          <p style={{ color: "var(--nova-text-2)" }}>Enter the 6-digit security code generated by your Authenticator app.</p>
          <form onSubmit={handleVerifyTotp} style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <Input label="6-Digit TOTP Code" value={totpCode} onChange={(e) => setTotpCode(e.target.value)} required />
            {error ? <p style={{ color: "var(--nova-danger)" }}>{error}</p> : null}
            <Button type="submit" block loading={busy}>Verify Code</Button>
          </form>
        </Card>
      </div>
    );
  }

  if (mfaStep === "email_otp") {
    const handleVerifyEmail = async (e: React.FormEvent) => {
      e.preventDefault();
      setError(null);
      setSuccessMessage(null);
      setBusy(true);
      try {
        const r = await api<{ accessToken: string }>(
          "/api/auth/mfa/verify-email",
          { method: "POST", body: { userId, code: emailOtpCode } }
        );
        onAuthed(r.accessToken);
      } catch (err) {
        setError((err as Error).message);
      } finally { setBusy(false); }
    };

    const handleResend = async () => {
      setError(null);
      setSuccessMessage(null);
      setBusy(true);
      try {
        const r = await api<{ status: string; userId: string; devEmailOtpCode?: string }>(
          "/api/auth/mfa/resend-email-otp",
          { method: "POST", body: { userId } }
        );
        if (r.devEmailOtpCode) setDevEmailOtpCode(r.devEmailOtpCode);
        setEmailOtpCode("");
        setSuccessMessage("A new verification code has been generated!");
      } catch (err) {
        setError((err as Error).message);
      } finally { setBusy(false); }
    };

    return (
      <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16 }}>
        <Card padded glow style={{ width: "100%", maxWidth: 420 }}>
          <h1 style={{ marginTop: 0 }}>3FA Step 3: Email OTP</h1>
          <p style={{ color: "var(--nova-text-2)" }}>A one-time passcode has been sent to your email address (and printed in server console logs).</p>
          
          {devEmailOtpCode ? (
            <div style={{ background: "rgba(124, 92, 255, 0.12)", border: "1px solid var(--nova-primary)", borderRadius: 8, padding: 12, textAlign: "center", marginBottom: 12 }}>
              <div style={{ fontSize: 12, color: "var(--nova-text-2)", marginBottom: 4 }}>DEMO OTP CODE</div>
              <div style={{ fontSize: 24, letterSpacing: 4, fontFamily: "monospace", color: "var(--nova-primary)", fontWeight: "bold" }}>{devEmailOtpCode}</div>
            </div>
          ) : null}

          {successMessage ? (
            <p style={{ color: "var(--nova-success)", margin: "0 0 12px 0", fontSize: 13, textAlign: "center", fontWeight: 600 }}>
              {successMessage}
            </p>
          ) : null}

          <form onSubmit={handleVerifyEmail} style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <Input label="6-Digit Email Code" value={emailOtpCode} onChange={(e) => setEmailOtpCode(e.target.value)} required />
            {error ? <p style={{ color: "var(--nova-danger)" }}>{error}</p> : null}
            <Button type="submit" block loading={busy}>Verify & Log In</Button>
          </form>

          <div style={{ textAlign: "center", marginTop: 14 }}>
            <button
              type="button"
              onClick={handleResend}
              disabled={busy}
              style={{
                background: "transparent",
                border: "none",
                color: "var(--nova-primary)",
                cursor: "pointer",
                fontSize: 13,
                fontWeight: 600,
                textDecoration: "underline",
                opacity: busy ? 0.6 : 1
              }}
            >
              Resend verification code
            </button>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 16 }}>
      <Card padded glow style={{ width: "100%", maxWidth: 420 }}>
        <h1 style={{ marginTop: 0 }}>Admin sign-in (3FA)</h1>
        <p style={{ color: "var(--nova-text-2)" }}>3-Factor Authentication is enabled for all operators. Please enter your email and password.</p>
        <form onSubmit={submit} style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <Input label="Email" value={identifier} onChange={(e) => setIdentifier(e.target.value)} />
          <Input label="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
          {error ? <p style={{ color: "var(--nova-danger)" }}>{error}</p> : null}
          <Button type="submit" block loading={busy}>Sign in</Button>
        </form>
      </Card>
    </div>
  );
}
